/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Loaded model and class list */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Diagnose a 23-d cycle feature vector */
        post: operations["predictFault"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate a cycle and diagnose it */
        post: operations["simulateCycle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Time series with a fault injected mid-trace */
        post: operations["getLiveTrace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One simulated point for the stats cards */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Class counts and headline metrics */
        get: operations["getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Short live trace for the activity strip */
        get: operations["getActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Named demo scenarios and whether the model matches */
        get: operations["getChallenges"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Classes, features, scenarios, and model card */
        get: operations["getCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Comparison table, confusion matrix, feature importance */
        get: operations["getModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dataset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dataset size, class mix, and column summaries */
        get: operations["getDataset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/explore/distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-class box stats for one feature */
        get: operations["getDistribution"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/explore/scatter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stratified scatter sample of two columns */
        get: operations["getScatter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/advanced": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Correlation matrix of cycle features */
        get: operations["getCorrelationMatrix"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/advanced/ambient": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fault counts by ambient-temperature bin */
        get: operations["getAmbientHeatmap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thermo/ph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** P-h diagram for one operating point */
        get: operations["getPhDiagram"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thermo/ph/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Nominal P-h overlay against condenser and evaporator load */
        get: operations["getPhCompare"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thermo/cop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Carnot envelope and measured Normal COP vs ambient */
        get: operations["getCopCurve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thermo/sweep/condenser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Condenser-load sweep of COP and compressor power */
        get: operations["getCondenserSweep"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thermo/sweep/evaporator": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source-temperature sweep of heating capacity */
        get: operations["getEvaporatorSweep"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thermo/ashrae": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** R410A saturation pressure vs the ASHRAE table */
        get: operations["getAshraeTable"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Headline cards from the results log */
        get: operations["getEvidenceSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/ladder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Truth ladder: each rung is one logged accuracy */
        get: operations["getEvidenceLadder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/protocols": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** X0b: feature sets against random-CV vs LOMO */
        get: operations["getEvidenceProtocols"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/references": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** X3 healthy-reference benchmark grid */
        get: operations["getEvidenceReferences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/per-class": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-class F1 on simulator vs NIST target vs transferred */
        get: operations["getEvidencePerClass"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paginated results.csv rows */
        get: operations["getEvidenceRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/confusion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Confusion matrix for a named protocol */
        get: operations["getEvidenceConfusion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityResponse */
        ActivityResponse: {
            /** Fault Type */
            fault_type: string;
            /** Inject At */
            inject_at: number;
            /** Trace */
            trace: components["schemas"]["LiveTracePoint"][];
        };
        /** AmbientHeatmapResponse */
        AmbientHeatmapResponse: {
            /** X Labels */
            x_labels: string[];
            /** Y Labels */
            y_labels: string[];
            /** Matrix */
            matrix: number[][];
        };
        /** AshraeResponse */
        AshraeResponse: {
            /** Coolprop */
            coolprop: boolean;
            /** Rows */
            rows: components["schemas"]["AshraeRow"][];
        };
        /** AshraeRow */
        AshraeRow: {
            /** T */
            T: number;
            /** Ashrae */
            ashrae: number;
            /** Coolprop */
            coolprop: number;
            /** Error Pct */
            error_pct: number;
        };
        /** BoxStats */
        BoxStats: {
            /** Name */
            name: string;
            /** Min */
            min: number;
            /** Q1 */
            q1: number;
            /** Median */
            median: number;
            /** Q3 */
            q3: number;
            /** Max */
            max: number;
            /** Mean */
            mean: number;
        };
        /** CatalogResponse */
        CatalogResponse: {
            /** Classes */
            classes: string[];
            /** Features */
            features: string[];
            /** Faults */
            faults: string[];
            /** Scenarios */
            scenarios: components["schemas"]["Scenario"][];
            model: components["schemas"]["ModelCard"];
        };
        /** Challenge */
        Challenge: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Injected */
            injected: string;
            /** Predicted */
            predicted: string;
            /** Confidence */
            confidence: number;
            /**
             * Status
             * @enum {string}
             */
            status: "On Going" | "Complete";
            /** Progress */
            progress: number;
        };
        /** ChallengesResponse */
        ChallengesResponse: {
            /** Challenges */
            challenges: components["schemas"]["Challenge"][];
        };
        /** ClassF1 */
        ClassF1: {
            /** Name */
            name: string;
            /** F1 */
            f1: number;
        };
        /** ClassShare */
        ClassShare: {
            /** Name */
            name: string;
            /** Value */
            value: number;
            /** Share */
            share: number;
        };
        /** ColumnStats */
        ColumnStats: {
            /** Mean */
            mean: number;
            /** Std */
            std: number;
            /** Min */
            min: number;
            /** Max */
            max: number;
        };
        /** ConfusionMatrix */
        ConfusionMatrix: {
            /** Labels */
            labels: string[];
            /** Matrix */
            matrix: number[][];
        };
        /** CopCurvePoint */
        CopCurvePoint: {
            /** T Amb */
            T_amb: number;
            /** Carnot */
            carnot: number;
            /** Estimated */
            estimated?: number | null;
            /** N */
            n?: number | null;
        };
        /** CopMeasuredPoint */
        CopMeasuredPoint: {
            /** T Amb */
            T_amb: number;
            /** Cop */
            COP: number;
        };
        /** CopResponse */
        CopResponse: {
            /** Curves */
            curves: components["schemas"]["CopCurvePoint"][];
            /** Measured */
            measured: components["schemas"]["CopMeasuredPoint"][];
        };
        /** CycleState */
        CycleState: {
            /** P Evap */
            P_evap: number;
            /** P Cond */
            P_cond: number;
            /** T Evap */
            T_evap: number;
            /** T Cond */
            T_cond: number;
            /** T Suction */
            T_suction: number;
            /** T Discharge */
            T_discharge: number;
            /** Superheat */
            superheat: number;
            /** Subcooling */
            subcooling: number;
            /** Compression Ratio */
            compression_ratio: number;
            /** W Comp */
            W_comp: number;
            /** Q Cond */
            Q_cond: number;
            /** Cop */
            COP: number;
        };
        /** DatasetResponse */
        DatasetResponse: {
            /** N Samples */
            n_samples: number;
            /** N Classes */
            n_classes: number;
            /** Normal Share */
            normal_share: number;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Describe */
            describe: {
                [key: string]: components["schemas"]["ColumnStats"];
            };
            /** Columns */
            columns: string[];
        };
        /** Diagnosis */
        Diagnosis: {
            /** Label */
            label: string;
            /** Confidence */
            confidence: number;
            /** Probabilities */
            probabilities: {
                [key: string]: number;
            };
        };
        /** DistributionResponse */
        DistributionResponse: {
            /** Feature */
            feature: string;
            /** Boxes */
            boxes: components["schemas"]["BoxStats"][];
        };
        /** Envelope */
        Envelope: {
            normal: components["schemas"]["EnvelopeZone"];
            extended: components["schemas"]["EnvelopeZone"];
        };
        /** EnvelopeZone */
        EnvelopeZone: {
            /** T Evap */
            T_evap: number[];
            /** T Cond */
            T_cond: number[];
        };
        /** EvidenceConfusion */
        EvidenceConfusion: {
            /** Protocol */
            protocol: string;
            /** Labels */
            labels: string[];
            /** Matrix */
            matrix: number[][];
            /** Source */
            source: string;
        };
        /** EvidenceLadder */
        EvidenceLadder: {
            /** Rungs */
            rungs: components["schemas"]["LadderRung"][];
            /** Majority */
            majority?: number | null;
        };
        /** EvidencePerClass */
        EvidencePerClass: {
            /** Rows */
            rows: components["schemas"]["PerClassScores"][];
            /** Notes */
            notes: string[];
            /** Protocols */
            protocols: {
                [key: string]: components["schemas"]["ProtocolRef"];
            };
        };
        /** EvidenceProtocols */
        EvidenceProtocols: {
            /** Series */
            series: components["schemas"]["ProtocolSlopePoint"][];
        };
        /** EvidenceReferences */
        EvidenceReferences: {
            /** Points */
            points: components["schemas"]["ReferencePoint"][];
            /** Majority */
            majority?: number | null;
            annotation_dmin0?: components["schemas"]["ReferencePoint"] | null;
            annotation_dmin05?: components["schemas"]["ReferencePoint"] | null;
        };
        /** EvidenceRuns */
        EvidenceRuns: {
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Rows */
            rows: components["schemas"]["RunRow"][];
            /**
             * Csv Path
             * @default outputs/results.csv
             */
            csv_path: string;
            /** Experiments */
            experiments?: string[];
            /** Protocols */
            protocols?: string[];
            /** Models */
            models?: string[];
            /** Labels */
            labels?: string[];
        };
        /** EvidenceSummary */
        EvidenceSummary: {
            /** N Experiments */
            n_experiments: number;
            /** N Measurements */
            n_measurements: number;
            /** N Protocols */
            n_protocols: number;
            /** Headline Value */
            headline_value?: number | null;
            /** Headline Percent */
            headline_percent?: number | null;
            headline_protocol?: components["schemas"]["ProtocolRef"] | null;
            /** Cards */
            cards: components["schemas"]["SummaryCard"][];
        };
        /**
         * FaultLabel
         * @description Labels the trained classifier can emit (and inject).
         * @enum {string}
         */
        FaultLabel: "Normal" | "Condenser_Fouling" | "Evaporator_Fouling" | "Refrigerant_Undercharge" | "Refrigerant_Overcharge" | "Condenser_Fan_Fault" | "Evaporator_Fan_Fault";
        /** FeatureImportance */
        FeatureImportance: {
            /** Feature */
            feature: string;
            /** Importance */
            importance: number;
        };
        /**
         * FeatureVector
         * @description 23-d cycle vector consumed by the classifier (P5: pressure_ratio dropped).
         */
        FeatureVector: {
            /** T Ambient */
            T_ambient: number;
            /** T Setpoint */
            T_setpoint: number;
            /** Compressor Speed Ratio */
            compressor_speed_ratio: number;
            /** P Evap */
            P_evap: number;
            /** P Cond */
            P_cond: number;
            /** T Evap */
            T_evap: number;
            /** T Cond */
            T_cond: number;
            /** T Suction */
            T_suction: number;
            /** T Discharge */
            T_discharge: number;
            /** Superheat */
            superheat: number;
            /** Subcooling */
            subcooling: number;
            /** Compression Ratio */
            compression_ratio: number;
            /** W Comp */
            W_comp: number;
            /** Q Cond */
            Q_cond: number;
            /** Cop */
            COP: number;
            /** Delta T Evap */
            delta_T_evap: number;
            /** Delta T Cond */
            delta_T_cond: number;
            /** Capacity Ratio */
            capacity_ratio: number;
            /** D T Discharge */
            d_T_discharge: number;
            /** D Superheat */
            d_superheat: number;
            /** D Subcooling */
            d_subcooling: number;
            /** D Cop */
            d_COP: number;
            /** D W Comp */
            d_W_comp: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Model */
            model: string;
            /** Classes */
            classes: string[];
        };
        /** LadderRung */
        LadderRung: {
            /** Value */
            value: number;
            /** Percent */
            percent: number;
            /** Cause */
            cause: string;
            /** Band */
            band: string;
            /**
             * Majority
             * @default false
             */
            majority: boolean;
            protocol: components["schemas"]["ProtocolRef"];
        };
        /** LiveRequest */
        LiveRequest: {
            /**
             * T Source
             * @default 7
             */
            T_source: number;
            /**
             * T Sink
             * @default 40
             */
            T_sink: number;
            /**
             * Speed Ratio
             * @default 0.7
             */
            speed_ratio: number;
            /** @default Condenser_Fouling */
            fault_type: components["schemas"]["FaultLabel"];
            /**
             * Inject At
             * @default 25
             */
            inject_at: number;
            /**
             * N Points
             * @default 60
             */
            n_points: number;
            /**
             * Severity Final
             * @default 0.4
             */
            severity_final: number;
        };
        /** LiveResponse */
        LiveResponse: {
            /** Trace */
            trace: components["schemas"]["LiveTracePoint"][];
        };
        /** LiveTracePoint */
        LiveTracePoint: {
            /** T */
            t: number;
            /** Injected Fault */
            injected_fault: string;
            /** Severity */
            severity: number;
            /** Predicted */
            predicted: string;
            /** Confidence */
            confidence: number;
            /** P Evap */
            P_evap: number;
            /** P Cond */
            P_cond: number;
            /** T Discharge */
            T_discharge: number;
            /** Superheat */
            superheat: number;
            /** Subcooling */
            subcooling: number;
            /** Cop */
            COP: number;
        } & {
            [key: string]: unknown;
        };
        /** MatrixResponse */
        MatrixResponse: {
            /** Labels */
            labels: string[];
            /** Matrix */
            matrix: number[][];
        };
        /** ModelCard */
        ModelCard: {
            /** Name */
            name: string;
            /** Accuracy */
            accuracy?: number | null;
            /** Precision */
            precision?: number | null;
            /** Recall */
            recall?: number | null;
            /** F1 */
            f1?: number | null;
            /** F1 Per Class */
            f1_per_class?: {
                [key: string]: number;
            };
            /** N Samples */
            n_samples?: number | null;
            /** N Features */
            n_features?: number | null;
            /**
             * Calibrated
             * @default true
             */
            calibrated: boolean;
            /**
             * Coolprop
             * @default true
             */
            coolprop: boolean;
        };
        /** ModelComparisonRow */
        ModelComparisonRow: {
            /** Model */
            Model: string;
            /** Accuracy */
            Accuracy: number;
            /** Precision */
            Precision: number;
            /** Recall */
            Recall: number;
            /** F1 Score */
            "F1 Score": number;
        };
        /** ModelsResponse */
        ModelsResponse: {
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Comparison */
            comparison: components["schemas"]["ModelComparisonRow"][];
            confusion: components["schemas"]["ConfusionMatrix"];
            /** Importance */
            importance: components["schemas"]["FeatureImportance"][];
            /** F1 Per Class */
            f1_per_class: components["schemas"]["ClassF1"][];
        };
        /** OperatingConditions */
        OperatingConditions: {
            /** T Source */
            T_source: number;
            /** T Sink */
            T_sink: number;
            /** Speed Ratio */
            speed_ratio: number;
            /** Injected Fault */
            injected_fault: string;
        };
        /** OverviewResponse */
        OverviewResponse: {
            /** Total */
            total: number;
            /** Classes */
            classes: components["schemas"]["ClassShare"][];
            /** F1 */
            f1?: number | null;
            /** Accuracy */
            accuracy?: number | null;
        };
        /** PerClassScores */
        PerClassScores: {
            /** Display */
            display: string;
            /** Simulated */
            simulated?: number | null;
            /** Target */
            target?: number | null;
            /** Transferred */
            transferred?: number | null;
        };
        /** PhCompareResponse */
        PhCompareResponse: {
            /** Coolprop */
            coolprop: boolean;
            /** Scenario */
            scenario: string;
            /** Saturation */
            saturation: components["schemas"]["SaturationPoint"][];
            nominal: components["schemas"]["PhOverlay"];
            condenser?: components["schemas"]["PhOverlay"] | null;
            evaporator?: components["schemas"]["PhOverlay"] | null;
        };
        /** PhCyclePoint */
        PhCyclePoint: {
            /** Name */
            name: string;
            /** H */
            h: number;
            /** P */
            P: number;
        };
        /** PhOverlay */
        PhOverlay: {
            /** T Evap */
            T_evap: number;
            /** T Cond */
            T_cond: number;
            /** P Evap */
            P_evap: number;
            /** P Cond */
            P_cond: number;
            /** Cop */
            COP: number;
            /** Cycle */
            cycle: components["schemas"]["PhCyclePoint"][];
        };
        /** PhResponse */
        PhResponse: {
            /** Coolprop */
            coolprop: boolean;
            /** P Evap */
            P_evap: number;
            /** P Cond */
            P_cond: number;
            /** Cop */
            COP: number;
            /** Saturation */
            saturation: components["schemas"]["SaturationPoint"][];
            /** Cycle */
            cycle: components["schemas"]["PhCyclePoint"][];
            envelope: components["schemas"]["Envelope"];
        };
        /** PredictRequest */
        PredictRequest: {
            features: components["schemas"]["FeatureVector"];
        };
        /** ProtocolRef */
        ProtocolRef: {
            /** Experiment */
            experiment: string;
            /** Protocol */
            protocol: string;
            /** Reference */
            reference: string;
            /**
             * Features
             * @default
             */
            features: string;
            /**
             * Model
             * @default
             */
            model: string;
        };
        /** ProtocolSlopePoint */
        ProtocolSlopePoint: {
            /** Features */
            features: string;
            /** Random Cv */
            random_cv?: number | null;
            /** Lomo */
            lomo?: number | null;
            protocol_cv?: components["schemas"]["ProtocolRef"] | null;
            protocol_lomo?: components["schemas"]["ProtocolRef"] | null;
        };
        /** ReferencePoint */
        ReferencePoint: {
            /** Family */
            family: string;
            /** Facet */
            facet: string;
            /** Conditioning */
            conditioning: string;
            /** Dmin */
            dmin: number;
            /** Accuracy */
            accuracy: number;
            protocol: components["schemas"]["ProtocolRef"];
        };
        /** RunRow */
        RunRow: {
            /** Experiment */
            experiment: string;
            /** Protocol */
            protocol: string;
            /** Reference */
            reference: string;
            /** Features */
            features: string;
            /** Model */
            model: string;
            /** Label */
            label: string;
            /** Metric */
            metric: string;
            /** Value */
            value: number;
            /** N */
            n?: number | null;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** SaturationPoint */
        SaturationPoint: {
            /** T */
            T: number;
            /** P */
            P: number;
            /** H Liq */
            h_liq: number;
            /** H Vap */
            h_vap: number;
        };
        /** ScatterPoint */
        ScatterPoint: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Fault Type */
            fault_type: string;
        };
        /** ScatterResponse */
        ScatterResponse: {
            /** X */
            x: string;
            /** Y */
            y: string;
            /** Points */
            points: components["schemas"]["ScatterPoint"][];
        };
        /** Scenario */
        Scenario: {
            /** Title */
            title: string;
            /** Fault Type */
            fault_type: string;
            /** Params */
            params?: {
                [key: string]: number;
            };
            /** Description */
            description: string;
        };
        /** SimulateRequest */
        SimulateRequest: {
            /**
             * T Source
             * @description Evaporator source temperature °C
             * @default 7
             */
            T_source: number;
            /**
             * T Sink
             * @description Condenser sink temperature °C
             * @default 40
             */
            T_sink: number;
            /**
             * Speed Ratio
             * @default 0.7
             */
            speed_ratio: number;
            /** @default Normal */
            fault_type: components["schemas"]["FaultLabel"];
            /** Severity */
            severity?: number | null;
        };
        /** SimulateResponse */
        SimulateResponse: {
            conditions: components["schemas"]["OperatingConditions"];
            cycle: components["schemas"]["CycleState"];
            features: components["schemas"]["FeatureVector"];
            diagnosis: components["schemas"]["Diagnosis"];
        };
        /** StatsResponse */
        StatsResponse: {
            /** Fault Type */
            fault_type: string;
            /** Label */
            label: string;
            /** Confidence */
            confidence: number;
            /** Probabilities */
            probabilities: {
                [key: string]: number;
            };
            /** Cop */
            COP: number;
            /** P Cond */
            P_cond: number;
            /** P Evap */
            P_evap: number;
            /** T Discharge */
            T_discharge: number;
            /** Superheat */
            superheat: number;
            /** Subcooling */
            subcooling: number;
            /** Model */
            model: string;
        };
        /** SummaryCard */
        SummaryCard: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Value */
            value: string;
            protocol?: components["schemas"]["ProtocolRef"] | null;
        };
        /** SweepPoint */
        SweepPoint: {
            /** T Evap */
            T_evap: number;
            /** T Cond */
            T_cond: number;
            /** P Evap */
            P_evap: number;
            /** P Cond */
            P_cond: number;
            /** Tau */
            tau: number;
            /** Cop */
            COP: number;
            /** W Comp */
            W_comp: number;
            /** Q Cond */
            Q_cond: number;
            /** Q Evap */
            Q_evap: number;
            /** T Dis */
            T_dis: number;
            /** Load */
            load?: number | null;
            /** T Source */
            t_source?: number | null;
        };
        /** SweepResponse */
        SweepResponse: {
            /** Kind */
            kind: string;
            /** Coolprop */
            coolprop: boolean;
            /** Points */
            points: components["schemas"]["SweepPoint"][];
            /** Deltas */
            deltas: {
                [key: string]: number;
            };
            /** Headline */
            headline: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    predictFault: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredictRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Diagnosis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulateCycle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getLiveTrace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LiveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getStats: {
        parameters: {
            query?: {
                fault_type?: components["schemas"]["FaultLabel"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
        };
    };
    getActivity: {
        parameters: {
            query?: {
                fault_type?: components["schemas"]["FaultLabel"];
                inject_at?: number;
                n_points?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getChallenges: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengesResponse"];
                };
            };
        };
    };
    getCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogResponse"];
                };
            };
        };
    };
    getModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsResponse"];
                };
            };
        };
    };
    getDataset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetResponse"];
                };
            };
        };
    };
    getDistribution: {
        parameters: {
            query?: {
                feature?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistributionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getScatter: {
        parameters: {
            query?: {
                x?: string;
                y?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScatterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getCorrelationMatrix: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatrixResponse"];
                };
            };
        };
    };
    getAmbientHeatmap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AmbientHeatmapResponse"];
                };
            };
        };
    };
    getPhDiagram: {
        parameters: {
            query?: {
                T_evap?: number;
                T_cond?: number;
                superheat?: number;
                subcooling?: number;
                eta_is?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getPhCompare: {
        parameters: {
            query?: {
                T_evap?: number;
                T_cond?: number;
                superheat?: number;
                subcooling?: number;
                load_factor?: number;
                t_source?: number;
                scenario?: "nominal" | "condenser" | "evaporator" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhCompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getCopCurve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopResponse"];
                };
            };
        };
    };
    getCondenserSweep: {
        parameters: {
            query?: {
                T_evap?: number;
                load_min?: number;
                load_max?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SweepResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getEvaporatorSweep: {
        parameters: {
            query?: {
                T_cond?: number;
                source_min?: number;
                source_max?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SweepResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getAshraeTable: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AshraeResponse"];
                };
            };
        };
    };
    getEvidenceSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceSummary"];
                };
            };
        };
    };
    getEvidenceLadder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceLadder"];
                };
            };
        };
    };
    getEvidenceProtocols: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceProtocols"];
                };
            };
        };
    };
    getEvidenceReferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceReferences"];
                };
            };
        };
    };
    getEvidencePerClass: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidencePerClass"];
                };
            };
        };
    };
    getEvidenceRuns: {
        parameters: {
            query?: {
                experiment?: string | null;
                protocol?: string | null;
                model?: string | null;
                label?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceRuns"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getEvidenceConfusion: {
        parameters: {
            query?: {
                protocol?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceConfusion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
